[project]
name = "yt-most-replayed"
version = "0.1.0"
description = "A tool to extract and visualize YouTube's 'Most Replayed' data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "seaborn>=0.13.2",
    "yt-dlp>=2025.2.19",
]
